# Generated by Django 4.2 on 2025-03-02 10:28

from django.db import migrations
from django.contrib.auth.models import User
import time


def create_test_data(apps, schema_editor):
    superuser, created = User.objects.get_or_create(
        username="admin",
        defaults={"is_superuser": True, "is_staff": True}
    )
    if created:
        superuser.set_password("adminpassword")
        superuser.save()

    user, created = User.objects.get_or_create(
        username="testuser",
        defaults={"email": "test@mail.com", "is_superuser": False, "is_staff": False}
    )
    if created:
        user.set_password("testpassword")
        user.save()

    Task = apps.get_model("tasks", "Task")

    for i in range(1, 11):
        Task.objects.create(
            title=f"Test Task {i}",
            description=f"Description for task {i}",
            is_completed=False,
            author_id=user.id,
        )
        time.sleep(0.1)


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_test_data),
    ]
